In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Weather-2020-2025.csv")

In [3]:
#Quick look into the data
data.info()
data.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 52632 entries, 0 to 52631
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   location_id                    52632 non-null  int64
 1   time                           52632 non-null  str
 2   temperature_2m                 52632 non-null  float64
 3   relative_humidity_2m (%)       52632 non-null  int64
 4   wind_speed_10m (km/h)          52632 non-null  float64
 5   precipitation (mm)             52632 non-null  float64
 6   is_day                         52632 non-null  int64
 7   wind_speed_100m (km/h)         52632 non-null  float64
 8   wind_gusts_10m (km/h)          52632 non-null  float64
 9   wind_direction_100m            52632 non-null  int64
 10  wind_direction_10m             52632 non-null  int64
 11  cloud_cover (%)                52632 non-null  int64
 12  vapour_pressure_deficit (kPa)  52632 non-null  float64
dtypes: float64(6), int64(6), str(1)
memory usage: 5.2 MB

,location_id,time,temperature_2m,relative_humidity_2m (%),wind_speed_10m (km/h),precipitation (mm),is_day,wind_speed_100m (km/h),wind_gusts_10m (km/h),wind_direction_100m,wind_direction_10m,cloud_cover (%),vapour_pressure_deficit (kPa)
0,0,2024-01-01T00:00,7.7,77,30.6,0.0,0,48.2,51.8,246,243,90,0.25
1,0,2024-01-01T01:00,7.6,77,29.5,0.0,0,47.4,50.8,249,246,60,0.24
2,0,2024-01-01T02:00,7.3,78,29.0,0.0,0,47.0,49.3,248,245,22,0.22
3,0,2024-01-01T03:00,7.0,80,26.8,0.0,0,44.1,48.2,251,248,33,0.20
4,0,2024-01-01T04:00,6.9,80,26.0,0.0,0,42.7,44.6,254,251,46,0.20

In [4]:
#Remove null values
data.dropna()

,location_id,time,temperature_2m,relative_humidity_2m (%),wind_speed_10m (km/h),precipitation (mm),is_day,wind_speed_100m (km/h),wind_gusts_10m (km/h),wind_direction_100m,wind_direction_10m,cloud_cover (%),vapour_pressure_deficit (kPa)
0,0,2024-01-01T00:00,7.7,77,30.6,0.0,0,48.2,51.8,246,243,90,0.25
1,0,2024-01-01T01:00,7.6,77,29.5,0.0,0,47.4,50.8,249,246,60,0.24
2,0,2024-01-01T02:00,7.3,78,29.0,0.0,0,47.0,49.3,248,245,22,0.22
3,0,2024-01-01T03:00,7.0,80,26.8,0.0,0,44.1,48.2,251,248,33,0.20
4,0,2024-01-01T04:00,6.9,80,26.0,0.0,0,42.7,44.6,254,251,46,0.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52627,2,2025-12-31T19:00,10.4,86,6.1,0.0,0,13.0,11.9,65,45,100,0.17
52628,2,2025-12-31T20:00,10.4,87,5.7,0.0,0,13.1,11.9,77,58,100,0.17
52629,2,2025-12-31T21:00,10.6,87,5.5,0.0,0,13.3,11.2,91,67,100,0.16
52630,2,2025-12-31T22:00,10.5,89,9.0,0.0,0,19.8,16.2,106,91,100,0.14
52631,2,2025-12-31T23:00,10.1,87,10.1,0.0,0,21.9,19.8,104,87,100,0.16

In [5]:
#Max temp group
data.groupby("location_id")["temperature_2m"].max()

location_id
0    33.5
1    26.6
2    40.7
Name: temperature_2m, dtype: float64

In [6]:
#Min temp group 
data.groupby("location_id")["temperature_2m"].min()

location_id
0   -5.1
1   -3.1
2    5.1
Name: temperature_2m, dtype: float64

In [7]:
#Understanding the location of location 0
data.loc[data['temperature_2m'] == 33.5, ['time']]

                   time
13144  2025-07-01T16:00
38727  2024-05-31T15:00
40549  2024-08-15T13:00
41321  2024-09-16T17:00
48156  2025-06-28T12:00
49071  2025-08-05T15:00
49286  2025-08-14T14:00

In [8]:
#Understanding the location of location 1
data.loc[data['temperature_2m'] == 26.6, ['time']]

                   time
5083   2024-07-30T19:00
5365   2024-08-11T13:00
12851  2025-06-19T11:00
12925  2025-06-22T13:00
13127  2025-06-30T23:00
13150  2025-07-01T22:00
13379  2025-07-11T11:00
30929  2025-07-11T17:00
38657  2024-05-28T17:00
39374  2024-06-27T14:00
39471  2024-07-01T15:00
39539  2024-07-04T11:00
40006  2024-07-23T22:00
40068  2024-07-26T12:00
40144  2024-07-29T16:00
40188  2024-07-31T12:00
40237  2024-08-02T13:00
40291  2024-08-04T19:00
40338  2024-08-06T18:00
40382  2024-08-08T14:00
40958  2024-09-01T14:00
41631  2024-09-29T15:00
47879  2025-06-16T23:00
48216  2025-07-01T00:00
48330  2025-07-05T18:00
48371  2025-07-07T11:00
48400  2025-07-08T16:00
48520  2025-07-13T16:00
48546  2025-07-14T18:00
48826  2025-07-26T10:00
49210  2025-08-11T10:00
49553  2025-08-25T17:00
49645  2025-08-29T13:00
49646  2025-08-29T14:00
49766  2025-09-03T14:00
49767  2025-09-03T15:00
50824  2025-10-17T16:00

In [9]:
#Understanding the location of location 2
data.loc[data['temperature_2m'] == 40.7 , ['time']]

                   time
48184  2025-06-29T16:00
48207  2025-06-30T15:00

In [11]:
#Find entries per location
data.groupby("location_id").size()

location_id
0    17544
1    17544
2    17544
dtype: int64

In [15]:
#Reduce data frame to entries during the daytime
dayFilter = data[data["is_day"] == 1]
dayFilter

,location_id,time,temperature_2m,relative_humidity_2m (%),wind_speed_10m (km/h),precipitation (mm),is_day,wind_speed_100m (km/h),wind_gusts_10m (km/h),wind_direction_100m,wind_direction_10m,cloud_cover (%),vapour_pressure_deficit (kPa)
10,0,2024-01-01T10:00,6.3,69,19.3,0.0,1,34.1,32.8,259,256,99,0.30
11,0,2024-01-01T11:00,7.0,69,19.1,0.0,1,31.7,31.7,251,248,100,0.31
12,0,2024-01-01T12:00,7.8,69,18.2,0.0,1,29.4,32.4,239,236,100,0.33
13,0,2024-01-01T13:00,8.4,68,16.6,0.0,1,25.6,29.9,232,228,98,0.35
14,0,2024-01-01T14:00,8.4,75,15.4,0.0,1,23.0,28.1,215,213,100,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52622,2,2025-12-31T14:00,10.6,86,8.0,0.0,1,11.2,24.1,50,44,73,0.18
52623,2,2025-12-31T15:00,11.6,82,8.0,0.0,1,11.0,22.0,52,42,98,0.25
52624,2,2025-12-31T16:00,12.0,79,8.2,0.0,1,11.4,21.2,52,41,93,0.29
52625,2,2025-12-31T17:00,12.1,79,7.0,0.0,1,10.6,20.5,48,35,89,0.29
52626,2,2025-12-31T18:00,11.1,85,4.8,0.0,1,10.0,15.8,57,29,99,0.20

In [17]:
#Find how many entries have data during the day
dayFilter.groupby("location_id").size()

location_id
0    8989
1    8977
2    8945
dtype: int64

In [21]:
#Solar power works best when temp < 23°C
dayTempFilter = dayFilter[dayFilter['temperature_2m'] <23]
dayTempFilter

,location_id,time,temperature_2m,relative_humidity_2m (%),wind_speed_10m (km/h),precipitation (mm),is_day,wind_speed_100m (km/h),wind_gusts_10m (km/h),wind_direction_100m,wind_direction_10m,cloud_cover (%),vapour_pressure_deficit (kPa)
10,0,2024-01-01T10:00,6.3,69,19.3,0.0,1,34.1,32.8,259,256,99,0.30
11,0,2024-01-01T11:00,7.0,69,19.1,0.0,1,31.7,31.7,251,248,100,0.31
12,0,2024-01-01T12:00,7.8,69,18.2,0.0,1,29.4,32.4,239,236,100,0.33
13,0,2024-01-01T13:00,8.4,68,16.6,0.0,1,25.6,29.9,232,228,98,0.35
14,0,2024-01-01T14:00,8.4,75,15.4,0.0,1,23.0,28.1,215,213,100,0.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52622,2,2025-12-31T14:00,10.6,86,8.0,0.0,1,11.2,24.1,50,44,73,0.18
52623,2,2025-12-31T15:00,11.6,82,8.0,0.0,1,11.0,22.0,52,42,98,0.25
52624,2,2025-12-31T16:00,12.0,79,8.2,0.0,1,11.4,21.2,52,41,93,0.29
52625,2,2025-12-31T17:00,12.1,79,7.0,0.0,1,10.6,20.5,48,35,89,0.29
52626,2,2025-12-31T18:00,11.1,85,4.8,0.0,1,10.0,15.8,57,29,99,0.20

In [22]:
#Check how many entries are at the right time of day and temp
dayTempFilter.groupby("location_id").size()

location_id
0    8299
1    8950
2    6559
dtype: int64

In [24]:
#new dataframe that accounts for cloud cover
dayTempCloudFilter = dayTempFilter[dayTempFilter['cloud_cover (%)'] < 50]
dayTempCloudFilter

,location_id,time,temperature_2m,relative_humidity_2m (%),wind_speed_10m (km/h),precipitation (mm),is_day,wind_speed_100m (km/h),wind_gusts_10m (km/h),wind_direction_100m,wind_direction_10m,cloud_cover (%),vapour_pressure_deficit (kPa)
41,0,2024-01-02T17:00,10.9,75,52.3,0.0,1,79.5,87.5,243,242,27,0.33
64,0,2024-01-03T16:00,9.4,82,21.7,0.2,1,35.0,41.8,266,265,45,0.21
137,0,2024-01-06T17:00,4.9,84,10.7,0.0,1,21.5,24.1,350,346,12,0.14
154,0,2024-01-07T10:00,1.8,84,16.9,0.0,1,30.5,27.7,14,11,4,0.11
155,0,2024-01-07T11:00,3.2,78,20.0,0.0,1,28.8,32.4,26,23,21,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
52599,2,2025-12-30T15:00,11.3,86,7.5,0.0,1,9.7,22.0,56,50,13,0.18
52600,2,2025-12-30T16:00,11.6,85,7.5,0.0,1,9.7,20.5,42,35,2,0.21
52601,2,2025-12-30T17:00,11.6,84,6.5,0.0,1,8.9,19.4,42,30,1,0.22
52602,2,2025-12-30T18:00,10.6,88,4.8,0.0,1,9.9,15.5,53,31,1,0.15
52621,2,2025-12-31T13:00,9.4,89,10.0,0.0,1,13.3,23.0,63,62,45,0.12

In [25]:
#Find the size of the dataframe that filers temp, cloud and daytime
dayTempCloudFilter.groupby("location_id").size()

location_id
0    2427
1    2643
2    2961
dtype: int64